apiVersion: v1
kind: Namespace
metadata:
  name: vote
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: vote
  name: vote-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote-db
    spec:
      containers:
      - name: vote-db
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-db
spec:
  ports:
  - port: 6379
  selector:
    app: vote-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: vote
  name: vote-web
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-web
    spec:
      containers:
      - name: vote-web
        image: kangxhacrsea.azurecr.io/vote-web
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "vote-db"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: vote
  name: vote-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-api
    spec:
      containers:
      - name: vote-api
        image: kangxhacrsea.azurecr.io/vote-api
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "vote-db"
---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vote-web
---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vote-api