apiVersion: v1
kind: Namespace
metadata:
  name: vote
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: vote
  name: vote-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote-db
    spec:
      containers:
      - name: vote-db
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-db
spec:
  ports:
  - port: 6379
  selector:
    app: vote-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: vote
  name: vote-web
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-web
    spec:
      containers:
      - name: vote-web
        image: kangxhacrsea.azurecr.io/vote-web
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "vote-db"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: vote
  name: vote-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-api
    spec:
      containers:
      - name: vote-api
        image: kangxhacrsea.azurecr.io/vote-api
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "vote-db"
---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.100
  ports:
  - port: 80
  selector:
    app: vote-web
---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: vote-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.101
  ports:
  - port: 80
  selector:
    app: vote-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-vote-web
  namespace: vote
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: vote.kangxh.com
    http:
      paths:
      - path: /
        backend:
          serviceName: vote-web
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-vote-api
  namespace: vote
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /api/votes
spec:
  rules:
  - host: vote.kangxh.com
    http:
      paths:
      - path: /api/votes
        backend:
          serviceName: vote-api
          servicePort: 80