apiVersion: v1
kind: Namespace
metadata:
  name: task
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: task
  name: task-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: kangxhacrsea.azurecr.io/task-api
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  namespace: task
  name: task-api
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30030
  selector:
    app: task-api