apiVersion: v1
kind: Namespace
metadata:
  name: task
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: task
  name: task-api
spec:
  replicas: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: kangxhacrsea.azurecr.io/task-api
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  namespace: task
  name: task-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.110
  ports:
  - port: 80
  selector:
    app: task-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-task-api
  namespace: task
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: task.kangxh.com
    http:
      paths:
      - path: /
        backend:
          serviceName: task-api
          servicePort: 80