apiVersion: v1
kind: Namespace
metadata:
  name: ai
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: ai
  name: ocr-fr-labeltool
spec:
  replicas: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ocr-fr-labeltool
    spec:
      containers:
      - name: ocr-fr-labeltool
        image: mcr.microsoft.com/azure-cognitive-services/custom-form/labeltool:latest
        imagePullPolicy: "Always"
        args: ["EULA=accept"]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  namespace: ai
  name: ocr-fr-labeltool
spec:
  type: ClusterIP
  ports:
    - name: labeltool
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ocr-fr-labeltool
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ocr-fr-labeltool
  namespace: ai
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ocr-fr.kangxh.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ocr-fr-labeltool
          servicePort: 80