kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  namespace: db
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 31Gi