apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibean-deployment
  namespace: web
  labels:
    app: ibean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibean
  template:
    metadata:
      labels:
        app: ibean
    spec:
      containers:
      - name: ibean
        image: kangxhacrsea.azurecr.io/ibean.org:latest
        env:
          - name: AZUREFILE
            value: "/mnt/azure"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
        volumeMounts:
        - name: azure
          mountPath: /mnt/azure
      volumes:
      - name: azure
        azureFile:
          secretName: kangxhsaseaweb-secret
          shareName: web-ibean
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: ibean
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.240
  ports:
  - port: 80
  selector:
    app: ibean
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ibean
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.ibean.org
    http:
      paths:
      - path: /
        backend:
          serviceName: ibean
          servicePort: 80