apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: web
  name: kangxhweb
spec:
  replicas: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: kangxhweb
    spec:
      containers:
      - name: kangxhweb
        image: kangxhacrsea.azurecr.io/kangxh.com
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: kangxhweb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.0.220
  ports:
  - port: 80
  selector:
    app: kangxhweb
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-kangxhweb
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.kangxh.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kangxhweb
          servicePort: 80